"""Feels2

Revision ID: 20f2e08c0621
Revises: ad4622511e2f
Create Date: 2025-04-17 17:12:26.336052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20f2e08c0621'
down_revision: Union[str, None] = 'ad4622511e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperature_feels_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature_celsius_feels', sa.Float(), nullable=True),
    sa.Column('temperature_fahrenheit_feels', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('temperature_data', sa.Column('id_temperature_feels', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_temperature_data_temperature_feels', 'temperature_data', 'temperature_feels_data', ['id_temperature_feels'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_temperature_data_temperature_feels', 'temperature_data', type_='foreignkey')
    op.drop_column('temperature_data', 'id_temperature_feels')
    op.drop_table('temperature_feels_data')
    # ### end Alembic commands ###
