"""Feels

Revision ID: ad4622511e2f
Revises:
Create Date: 2025-04-17 17:09:32.379972

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad4622511e2f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "air_quality_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pressure_mb", sa.Float(), nullable=True),
        sa.Column("visibility_km", sa.Float(), nullable=True),
        sa.Column("uv_index", sa.Float(), nullable=True),
        sa.Column("air_quality_gb", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "celestial_events_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sunrise", sa.Time(), nullable=True),
        sa.Column("sunset", sa.Time(), nullable=True),
        sa.Column("moonrise", sa.Time(), nullable=True),
        sa.Column("moonset", sa.Time(), nullable=True),
        sa.Column("moon_phase", sa.String(length=50), nullable=True),
        sa.Column("moon_illumination", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "locations_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("location_name", sa.String(length=100), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "precipitation_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("precip_mm", sa.Float(), nullable=True),
        sa.Column("humidity", sa.Integer(), nullable=True),
        sa.Column("cloud", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "temperature_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("temperature_celsius", sa.Float(), nullable=True),
        sa.Column("temperature_fahrenheit", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wind_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wind_kph", sa.Float(), nullable=True),
        sa.Column("wind_degree", sa.Integer(), nullable=True),
        sa.Column(
            "wind_direction",
            sa.Enum(
                "N",
                "NNE",
                "NE",
                "ENE",
                "E",
                "ESE",
                "SE",
                "SSE",
                "S",
                "SSW",
                "SW",
                "WSW",
                "W",
                "WNW",
                "NW",
                "NNW",
                name="winddirection",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "weather_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.Column("celestial_id", sa.Integer(), nullable=True),
        sa.Column("air_quality_id", sa.Integer(), nullable=True),
        sa.Column("precipitation_id", sa.Integer(), nullable=True),
        sa.Column("wind_id", sa.Integer(), nullable=True),
        sa.Column("temperature_id", sa.Integer(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.Column("should_go_out", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["air_quality_id"],
            ["air_quality_data.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["celestial_id"],
            ["celestial_events_data.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations_data.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["precipitation_id"],
            ["precipitation_data.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["temperature_id"],
            ["temperature_data.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["wind_id"], ["wind_data.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_weather_data_last_updated"),
        "weather_data",
        ["last_updated"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weather_data_location_id"),
        "weather_data",
        ["location_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weather_data_location_id"), table_name="weather_data")
    op.drop_index(op.f("ix_weather_data_last_updated"), table_name="weather_data")
    op.drop_table("weather_data")
    op.drop_table("wind_data")
    op.drop_table("temperature_data")
    op.drop_table("precipitation_data")
    op.drop_table("locations_data")
    op.drop_table("celestial_events_data")
    op.drop_table("air_quality_data")
    # ### end Alembic commands ###
    bind = op.get_bind()

    # Додатково — перевірка для PostgreSQL enum
    if bind.dialect.name == "postgresql":
        op.execute("DROP TYPE IF EXISTS winddirection;")
